### ISSUE TITLE
ImportPage landing for profiler web app

### ISSUE THREAD

**Issue by kartikcho** [MLH-Fellowship/scheduling-profiler-prototype#41]
Made a mockup for the scheduling-profiler web app landing

![react-profiler](https://user-images.githubusercontent.com/48270786/86235236-bc3fe480-bbb5-11ea-8d9d-55a1d7f7264a.png)

**Comment by taneliang** [comment]
Duplicate of #9?

**Comment by kartikcho** [comment]
Not really, #9 was about the button implementation, this issue is for the page and design. Both will be covered under one PR soon though.
