### ISSUE TITLE
Upstream Speedscope code

### ISSUE THREAD

**Issue by taneliang** [MLH-Fellowship/scheduling-profiler-prototype#69]
From Brian's 17 July email and [doc](https://docs.google.com/document/d/1_UKje2GuvQhstXWeVsQwHMJ3qc80-bMaTrTMfAP5c4o/edit#):

> Upstream Speedscope timing patch ([6feb987](https://github.com/taneliang/speedscope/commit/6feb987dde8fa6e42c7d798b0a4f6e7d86a6dbc9))

https://github.com/MLH-Fellowship/scheduling-profiler-prototype/pull/53 added a custom Speedscope fork that fixes its handling of negative time deltas and also exports its internals for our use. We should look into pushing these back upstream.

Although Brian only mentioned that we should upstream the timing patch, we may also want to upstream the internals exporting as well so that we don't have to maintain our own fork. This should not be done so soon as we may have more requirements for Speedscope after adding Firefox support (#52).

**Comment by taneliang** [comment]
PR to upstream alignment fix: https://github.com/jlfwong/speedscope/pull/305

**Comment by taneliang** [comment]
@bvaughn, we have a bit of a problem here.

The Speedscope timing patch has been upstreamed, but the Speedscope maintainer would prefer not to expose Speedscope internals upstream, so we'll either have to maintain our own fork (which we're doing now; the diff can be found at https://github.com/taneliang/speedscope/compare/master...taneliang:fork-for-scheduling-profiler) or inline Speedscope code into our codebase.

I suspect it'll be easier to maintain the fork since our changes are mostly additive, and if Speedscope's codebase doesn't change too drastically we'll be able to update the fork by just rebasing our 2 commits. It'll be very helpful to keep up to date with the latest upstream changes as Chrome profile specs seem to change rather often and I don't think we'll want to fix them ourselves.

However, @jevakallio mentioned that React/FB would often rather inline the codebase. Do you have any preference?

**Comment by bvaughn** [comment]
I think the rationale for maintaining a fork sounds good.

**Comment by taneliang** [comment]
Cool! This task is complete then 👍
